version: "3"
services:
  app:
    container_name: express-mongo
    restart: always
    build: ./
    ports:
      - "80:3000"
    volumes:
      - .:/app
      - /log
    links:
      - mongo
    command: npm run dev
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
